package com.accounting.service;

import com.accounting.model.Document;
import com.accounting.model.enums.DocumentStatus;
import com.accounting.model.enums.DocumentType;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.multipart.MultipartFile;
import java.util.List;
import java.util.Map;
import java.util.Optional;

public interface DocumentService {
    Document uploadDocument(MultipartFile file, DocumentType type, String username);
    Document saveDocument(Document document, MultipartFile file);
    Document downloadDocument(Long id);
    Document getDocumentById(Long id);
    List<Document> getDocumentsByUser(String username);
    List<Document> getDocumentsByType(DocumentType type);
    List<Document> getDocumentsByStatus(DocumentStatus status);
    List<Document> getDocumentsByDescription(String description);
    void deleteDocument(Long id);
    Document updateDocument(Long id, Document document);
    long getDocumentCount();
    long getDocumentCountByUser(String username);
    long getDocumentCountByType(DocumentType type);
    long getDocumentCountByStatus(DocumentStatus status);
    List<Document> getDocumentsByReferenceId(Long referenceId);
    Optional<Document> getDocument(Long id);
    Document updateDocumentStatus(Long id, DocumentStatus status);
    long countDocumentsByType(String type);
    long countDocumentsByType(DocumentType type);
    long countDocumentsByStatus(String status);
    long countDocumentsByStatus(DocumentStatus status);
    byte[] getDocumentContent(Long id);
    String getDocumentFileName(Long id);
    String getDocumentFilename(Long id);
    String getDocumentContentType(Long id);
    long getDocumentSize(Long id);
    List<Document> getDocumentsByTransactionId(Long transactionId);
    long countDocumentsByUser(String username);
    List<Document> getStudentDocuments(Long studentId);
    List<Document> getRecentDocuments(Long studentId, int limit);
    Document save(Document document);
    List<Document> findAll();
    Document findById(Long id);
    void deleteById(Long id);
    Page<Document> findAll(Pageable pageable);
    List<Document> findByUserUsername(String username);
    List<Document> findByStatus(DocumentStatus status);
    Page<Document> findByStatus(DocumentStatus status, Pageable pageable);
    List<Document> findByType(DocumentType type);
    Page<Document> findByType(DocumentType type, Pageable pageable);
    Page<Document> findByStatusAndType(DocumentStatus status, DocumentType type, Pageable pageable);
    Page<Document> searchDocuments(String searchTerm, Pageable pageable);
    Document updateDocumentStatus(Long id, DocumentStatus status, String comment);
    List<Map<String, Object>> getDocumentHistory(Long id);
    void addComment(Long id, String comment);
    long getTotalDocumentsCount();
} 