<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<div class="admin-content">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Reports Management</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <button type="button" class="btn btn-primary" onclick="generateReport()">
                <i class="bi bi-file-earmark-text"></i> Generate Report
            </button>
        </div>
    </div>

    <!-- Report Filters -->
    <div class="card shadow mb-4">
        <div class="card-header">
            <h5 class="mb-0">Report Filters</h5>
        </div>
        <div class="card-body">
            <form id="reportFilters">
                <div class="row">
                    <div class="col-md-3">
                        <div class="mb-3">
                            <label class="form-label">Report Type</label>
                            <select class="form-select" id="reportType" required>
                                <option value="">Select Report Type</option>
                                <option value="TRANSACTION">Transaction Report</option>
                                <option value="USER">User Report</option>
                                <option value="QUEUE">Queue Report</option>
                                <option value="FINANCIAL">Financial Report</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-3">
                            <label class="form-label">Date Range</label>
                            <select class="form-select" id="dateRange">
                                <option value="TODAY">Today</option>
                                <option value="WEEK">This Week</option>
                                <option value="MONTH">This Month</option>
                                <option value="YEAR">This Year</option>
                                <option value="CUSTOM">Custom Range</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-3">
                            <label class="form-label">Start Date</label>
                            <input type="date" class="form-control" id="startDate">
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-3">
                            <label class="form-label">End Date</label>
                            <input type="date" class="form-control" id="endDate">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        <div class="mb-3">
                            <label class="form-label">Format</label>
                            <select class="form-select" id="reportFormat">
                                <option value="PDF">PDF</option>
                                <option value="EXCEL">Excel</option>
                                <option value="CSV">CSV</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="mb-3">
                            <label class="form-label">Group By</label>
                            <select class="form-select" id="groupBy">
                                <option value="NONE">None</option>
                                <option value="DAY">Day</option>
                                <option value="WEEK">Week</option>
                                <option value="MONTH">Month</option>
                                <option value="YEAR">Year</option>
                            </select>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Apply Filters</button>
            </form>
        </div>
    </div>

    <!-- Report Preview -->
    <div class="card shadow">
        <div class="card-header">
            <h5 class="mb-0">Report Preview</h5>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Report ID</th>
                            <th>Type</th>
                            <th>Date Range</th>
                            <th>Generated By</th>
                            <th>Generated At</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="reportTableBody">
                        <c:forEach items="${reports}" var="report">
                            <tr>
                                <td>${report.id}</td>
                                <td>${report.type}</td>
                                <td>
                                    <fmt:formatDate value="${report.startDate}" pattern="yyyy-MM-dd"/> to
                                    <fmt:formatDate value="${report.endDate}" pattern="yyyy-MM-dd"/>
                                </td>
                                <td>${report.generatedBy.username}</td>
                                <td><fmt:formatDate value="${report.generatedAt}" pattern="yyyy-MM-dd HH:mm"/></td>
                                <td>
                                    <span class="badge bg-${report.status == 'COMPLETED' ? 'success' : 
                                                          report.status == 'PROCESSING' ? 'warning' : 'danger'}">
                                        ${report.status}
                                    </span>
                                </td>
                                <td>
                                    <button class="btn btn-sm btn-primary" onclick="downloadReport('${report.id}')">
                                        <i class="bi bi-download"></i>
                                    </button>
                                    <button class="btn btn-sm btn-danger" onclick="deleteReport('${report.id}')">
                                        <i class="bi bi-trash"></i>
                                    </button>
                                </td>
                            </tr>
                        </c:forEach>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- Report Statistics -->
    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-body text-center">
                    <h5 class="card-title">Total Reports</h5>
                    <h2 class="display-4">${totalReports}</h2>
                    <p class="text-muted">Generated</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-body text-center">
                    <h5 class="card-title">Average Size</h5>
                    <h2 class="display-4">${averageSize} MB</h2>
                    <p class="text-muted">Per Report</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-body text-center">
                    <h5 class="card-title">Storage Used</h5>
                    <h2 class="display-4">${storageUsed} GB</h2>
                    <p class="text-muted">Total</p>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('dateRange').addEventListener('change', function() {
        const customRange = this.value === 'CUSTOM';
        document.getElementById('startDate').disabled = !customRange;
        document.getElementById('endDate').disabled = !customRange;
    });

    function generateReport() {
        const form = document.getElementById('reportFilters');
        const formData = new FormData(form);
        const reportData = {
            type: formData.get('reportType'),
            dateRange: formData.get('dateRange'),
            startDate: formData.get('startDate'),
            endDate: formData.get('endDate'),
            format: formData.get('reportFormat'),
            groupBy: formData.get('groupBy')
        };

        fetch(`${pageContext.request.contextPath}/admin/reports/generate`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(reportData)
        })
        .then(response => {
            if (response.ok) {
                window.location.reload();
            } else {
                throw new Error('Failed to generate report');
            }
        })
        .catch(error => {
            alert(error.message);
        });
    }

    function downloadReport(reportId) {
        window.location.href = `${pageContext.request.contextPath}/admin/reports/${reportId}/download`;
    }

    function deleteReport(reportId) {
        if (confirm('Are you sure you want to delete this report?')) {
            fetch(`${pageContext.request.contextPath}/admin/reports/${reportId}`, {
                method: 'DELETE'
            })
            .then(response => {
                if (response.ok) {
                    window.location.reload();
                } else {
                    throw new Error('Failed to delete report');
                }
            })
            .catch(error => {
                alert(error.message);
            });
        }
    }
</script> 