<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

<div class="manager-reports">
    <div class="content-header">
        <h1 class="h2">Reports</h1>
        <div class="header-actions">
            <button class="btn btn-primary" onclick="generateReport()">
                <i class="bi bi-file-earmark-text"></i> Generate Report
            </button>
            <button class="btn btn-success" onclick="exportReport()">
                <i class="bi bi-download"></i> Export
            </button>
        </div>
    </div>

    <!-- Report Filters -->
    <div class="card mb-4">
        <div class="card-body">
            <form id="reportFilters" class="row g-3">
                <div class="col-md-3">
                    <label class="form-label">Report Type</label>
                    <select class="form-select" name="reportType" onchange="updateFilterOptions()">
                        <option value="financial">Financial Report</option>
                        <option value="user">User Activity Report</option>
                        <option value="transaction">Transaction Report</option>
                        <option value="system">System Performance Report</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Date Range</label>
                    <select class="form-select" name="dateRange">
                        <option value="today">Today</option>
                        <option value="week">This Week</option>
                        <option value="month">This Month</option>
                        <option value="quarter">This Quarter</option>
                        <option value="year">This Year</option>
                        <option value="custom">Custom Range</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label class="form-label">Format</label>
                    <select class="form-select" name="format">
                        <option value="pdf">PDF</option>
                        <option value="excel">Excel</option>
                        <option value="csv">CSV</option>
                    </select>
                </div>
                <div class="col-md-3">
                    <label class="form-label">&nbsp;</label>
                    <button type="submit" class="btn btn-primary w-100">
                        <i class="bi bi-search"></i> Generate
                    </button>
                </div>
            </form>
        </div>
    </div>

    <!-- Report Results -->
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5>Report Results</h5>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Report Type</th>
                                    <th>Generated By</th>
                                    <th>Status</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <c:forEach items="${reports}" var="report">
                                    <tr>
                                        <td><fmt:formatDate value="${report.generatedDate}" pattern="MMM dd, yyyy HH:mm"/></td>
                                        <td>${report.type}</td>
                                        <td>${report.generatedBy}</td>
                                        <td>
                                            <span class="badge ${report.status == 'COMPLETED' ? 'bg-success' : 
                                                              report.status == 'PROCESSING' ? 'bg-warning' : 'bg-danger'}">
                                                ${report.status}
                                            </span>
                                        </td>
                                        <td>
                                            <button class="btn btn-sm btn-primary" onclick="viewReport('${report.id}')">
                                                <i class="bi bi-eye"></i>
                                            </button>
                                            <button class="btn btn-sm btn-success" onclick="downloadReport('${report.id}')">
                                                <i class="bi bi-download"></i>
                                            </button>
                                        </td>
                                    </tr>
                                </c:forEach>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h5>Report Statistics</h5>
                </div>
                <div class="card-body">
                    <div class="stat-item">
                        <h6>Total Reports Generated</h6>
                        <p class="stat-value">${totalReports}</p>
                    </div>
                    <div class="stat-item">
                        <h6>Average Generation Time</h6>
                        <p class="stat-value">${avgGenerationTime} seconds</p>
                    </div>
                    <div class="stat-item">
                        <h6>Most Popular Report</h6>
                        <p class="stat-value">${mostPopularReport}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .manager-reports {
        padding: 2rem;
    }

    .stat-item {
        margin-bottom: 1.5rem;
    }

    .stat-item h6 {
        color: var(--text-color);
        font-size: 0.875rem;
        margin-bottom: 0.5rem;
    }

    .stat-value {
        color: var(--primary-color);
        font-size: 1.25rem;
        font-weight: 600;
        margin: 0;
    }

    .table th {
        background-color: var(--light-color);
    }
</style>

<script>
    function updateFilterOptions() {
        const reportType = document.querySelector('select[name="reportType"]').value;
        const dateRangeSelect = document.querySelector('select[name="dateRange"]');
        
        // Update date range options based on report type
        if (reportType === 'financial') {
            dateRangeSelect.innerHTML = `
                <option value="today">Today</option>
                <option value="week">This Week</option>
                <option value="month">This Month</option>
                <option value="quarter">This Quarter</option>
                <option value="year">This Year</option>
                <option value="custom">Custom Range</option>
            `;
        } else if (reportType === 'system') {
            dateRangeSelect.innerHTML = `
                <option value="hour">Last Hour</option>
                <option value="day">Last 24 Hours</option>
                <option value="week">Last Week</option>
                <option value="month">Last Month</option>
            `;
        }
    }

    function generateReport() {
        const form = document.getElementById('reportFilters');
        const formData = new FormData(form);
        
        // Show loading state
        const submitButton = form.querySelector('button[type="submit"]');
        submitButton.disabled = true;
        submitButton.innerHTML = '<i class="bi bi-hourglass-split"></i> Generating...';
        
        // Simulate report generation
        setTimeout(() => {
            submitButton.disabled = false;
            submitButton.innerHTML = '<i class="bi bi-search"></i> Generate';
            alert('Report generated successfully!');
        }, 2000);
    }

    function exportReport() {
        // Implement export functionality
        console.log('Exporting report...');
    }

    function viewReport(reportId) {
        // Implement view report functionality
        console.log('Viewing report:', reportId);
    }

    function downloadReport(reportId) {
        // Implement download functionality
        console.log('Downloading report:', reportId);
    }
</script> 